version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE_URL
        - NEXT_PUBLIC_ENVIRONMENT
        - NEXT_PUBLIC_SITE_URL
        - SUPERADMIN
        - GITHUB_CLIENT_ID
        - GITHUB_CLIENT_SECRET
        - OPENAI_API_KEY
        - UPLOADTHING_SECRET
        - UPLOADTHING_APP_ID
        - UPSTASH_REDIS_REST_URL
        - UPSTASH_REDIS_REST_TOKEN
        - GITHUB_AUTH_TOKEN
    env_file:
      - .env.local
    ports:
      - '3000:3000'
